PUT http://localhost:5000/users/updateUser/CEhyALaJglXuK92zARwJDiaTwDi2

{
    "name":"Praveen08"
}

###

POST http://localhost:5000/posts/createpost

{
    "post":"Golang is Awesome",
    "email":"Praveenkusuluri08@gmail.com",
    "isExists":true,
    "likesCount":0,
    "commentsCount":0

}
###

GET http://localhost:5000/posts/getallposts

###

POST http://localhost:5000/posts/commentonpost/NqICEIeOA1ZEMVegUsEK

{
    "comment":"Golang 💌",
    "email":"Praveenkusuluri08@gmail.com"
}

###

GET http://localhost:5000/posts/getsinglepost/NqICEIeOA1ZEMVegUsEK